development: &development
  WeatherApi:
    Appid: "69075f"
    Url: "http://api.openweathermap.org/data/2.5/weather"
  SpotifyApi:
    ClientId: "dbe6"
    SecretKey: "6556"

staging:
  <<: *development

production:
  <<: *development

