development: &development
  BardApi:
    Port: 8088
  WeatherApi:
    Appid: "69075f"
    Url: "http://api.openweathermap.org/data/2.5/weather"
  SpotifyApi:
    ClientId: "dbe6"
    SecretKey: "6556"
  Memcache:
    Host: "172.17.0.2:11211"

staging:
  <<: *development

production:
  <<: *development

