development:
  hostname: 'gagarin001'
  build: .
  dockerfile: './Dockerfile'
  tty: true
  stdin_open: true
  command: >
    bash -c "tail -f /var/log/apt/history.log"
  volumes:
    - .:/go/src/github.com/hcsouza/bard


