development:
  hostname: 'gagarin001'
  build: .
  dockerfile: './Dockerfile'
  tty: true
  stdin_open: true
  command: >
    bash -c "dep ensure --vendor-only &&
    tail -f /var/log/apt/history.log"
  volumes:
    - .:/go/src/github.com/hcsouza/bard
  environment:
    ENV: "development"
  links:
    - memcached:memcached

memcached:
  image: memcached
  ports:
    - "11211:11211"


