apiVersion: v1
kind: Pod
metadata:
  name: memcache
  labels:
    app: memcache
spec:
  containers:
  - name: memcache
    image: registry.hub.docker.com/library/memcached:latest
    ports:
    - containerPort: 11211
---
apiVersion: v1
kind: Service
metadata:
  name: memcache
spec:
  selector:
    app: memcache
  ports:
  - protocol: TCP
    port: 11211
    targetPort: 11211
