---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bard-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bard-api
  template:
    metadata:
      labels:
        app: bard-api
    spec:
      containers:
      - name: bard-api
        image: hcsouza/bardapi-kubernetes:1.0.1
        imagePullPolicy: Always
        ports:
          - containerPort: 8088
          - containerPort: 81

---

apiVersion: v1
kind: Service
metadata:
  name: bard-api-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 9090
    targetPort: 8088
  selector:
    app: bard-api
---
apiVersion: v1
kind: Service
metadata:
  name: bard-metrics-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 9090
    targetPort: 81
  selector:
    app: bard-api
